name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t samikshapawar29/wisecow-app:latest .
        docker push samikshapawar29/wisecow-app:latest

    - name: Install KinD
      run: |
        curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.17.0/kind-linux-amd64
        sudo chmod +x kind
        sudo mv kind /usr/local/bin/

    - name: Create KinD Cluster
      run: |
        kind create cluster

    - name: Set up kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
        sudo mv kubectl /usr/local/bin/
        sudo chmod +x /usr/local/bin/kubectl

    - name: Deploy to KinD Kubernetes Cluster
      run: |
        kubectl apply -f k8s/
